version: '3.8'

services:
  mysqldbservices:
    container_name: mysqldbcontainer
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root

  springbootappservices:
    container_name: springbootappcontainer
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depend_on:
      - mysqldbservices